bcgov/jasper

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
docker/manage

Added devcontainer config to be able to build and run jasper project and its components.

Dev env setup

---

.devcontainer/devcontainer.json
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/aws-bootstrap-template.yml
.github/workflows/aws-template-terraform.yml
.github/workflows/deploy-infra-sandbox.yml
Makefile
infrastructure/cloud/environments/sandbox/providers.tf
infrastructure/cloud/environments/sandbox/variables.tf
infrastructure/cloud/environments/sandbox/webapp.tf
infrastructure/cloud/modules/security/kms.tf
infrastructure/cloud/modules/security/outputs.tf
infrastructure/cloud/modules/security/variables.tf
infrastructure/cloud/modules/storage/s3buckets.tf
infrastructure/cloud/modules/storage/variables.tf
infrastructure/jasper-aws-bootstrap/.gitignore
infrastructure/jasper-aws-bootstrap/.npmignore
infrastructure/jasper-aws-bootstrap/README.md
infrastructure/jasper-aws-bootstrap/bin/jasper-aws-bootstrap.ts
infrastructure/jasper-aws-bootstrap/cdk.json
infrastructure/jasper-aws-bootstrap/jest.config.js
infrastructure/jasper-aws-bootstrap/lib/jasper-aws-bootstrap-stack.ts
infrastructure/jasper-aws-bootstrap/package.json
infrastructure/jasper-aws-bootstrap/test/jasper-aws-bootstrap.test.ts
infrastructure/jasper-aws-bootstrap/tsconfig.json

- Added AWS Setups
- Added CDK to Devcontainer
- Added some sample Terraform scripts and Workflow templates
- Added PR template

Added AWS Setups

---

web/src/components/dashboard/Dashboard.vue
web/src/router/index.ts

https://jag.gov.bc.ca/jira/browse/JASPER-64
Added a template for the judges' dashboard page layout. 
Further development will proceed as part of the upcoming stories JASPER-97, JASPER-65, JASPER-98, JASPER-71

Template for judges dashboard page layout

---

.github/workflows/sync-secrets.yml

https://jag.gov.bc.ca/jira/browse/JASPER-101
This is an initial commit so Github can recognize the action. The action needs to exist in master branch first.

JASPER-101: Initial changes to make the action accessible

---

web/src/components/NavigationTopbar.vue
web/src/styles/_header.scss

https://jag.gov.bc.ca/jira/browse/JASPER-97
Added header menu items, disabled all for now except the dashboard, and added the welcome message
Reviewed on page to ensure everything showed up as expected. Outstanding item: get user name and role to show on page
N/A

JASPER-97: Updates for header items on all pages

---

.github/workflows/publish-lambdas.yml

Initial code changes for the GHA to be available for manual trigger via GH UI.

Initial GHA for deploying Lambda functions to ECR

---

api/Infrastructure/ServiceCollectionExtensions.cs
docker/docker-compose.yaml

N/A
The recent updates to using API Gateway URLs and keys is causing issues for local development. This has been commented for now until mTLS connection is ready for testing.

Comment API Gateway related env variables

---

api/api.csproj
pcss-client/pcss-client.csproj

- Update recommendations provided by dependabot

Additional .net dependency updates

---

web/package-lock.json
web/package.json
web/src/components/civil/CivilDocumentsView.vue
web/src/components/courtlist/CourtList.vue
web/src/components/courtlist/CourtListLayout.vue
web/src/main.ts
web/src/shims-vue.d.ts
web/src/styles/index.scss
web/vite.config.js

https://jag.gov.bc.ca/jira/browse/JASPER-250
build: utilize bootstrap-vue-next
build: remove vue/compat
refactor: adhere to new styling framework
refactor: remove vue/compat setup
- Styling will look weirder as a result of this PR, moving to the Vue3 version of bootstrap-vue requires certain changes to make it look the same as its Vue2 equivalent, but this will be wasted time as we are going to replace it with Vuetify anyways
- Icons are no longer appearing on the site (bootstrap-vue-next deprecated icon support) but this will be fixed when Vuetify is introduced to the project

JASPER-250: Vue/Compat => Vue3 Migration

---

web/vite.config.js

Previous PR #99 accidentally set the target to http (used for local development), we want to target https in prod

Target https

---

web/src/components/courtfilesearch/CourtFileSearchView.vue

https://jag.gov.bc.ca/jira/browse/JASPER-177
PR to align Court File Search and it's filters closer to the mockups using Vuetify!
Note: This PR ignored the table results component, that will be another PR
I tried touching the JS as little as possible as it was working as it was
A lot of changes seem to be going on in this file, but overall amount of code was lowered
refactor: court file search follow mockups
refactor: script to composition api
https://vuejs.org/guide/extras/composition-api-faq.html
https://github.com/user-attachments/assets/75d9c857-8a7c-4e7b-887d-0591b7ab17bf

JASPER-177: Court File Search Filter Rework

---

.github/workflows/build-infra.yml
.github/workflows/publish-api.yml
.github/workflows/publish-infra.yml
.github/workflows/publish-web.yml
infrastructure/cloud/environments/prod/backend.tfvars
infrastructure/cloud/environments/prod/main.tf
infrastructure/cloud/environments/prod/prod.tfvars
infrastructure/cloud/environments/prod/providers.tf
infrastructure/cloud/environments/prod/variables.tf
infrastructure/cloud/modules/IAM/main.tf

https://jag.gov.bc.ca/jira/browse/JASPER-218
- Added `prod` terraform files
- Enable `prod` job for `web` and `api` pipelines.

JASPER-218: Deploy JASPER application to production - preliminary deployment

---

web/src/App.vue
web/src/components/courtlist/CourtList.vue
web/src/components/courtlist/CourtListLayout.vue
web/src/components/shared/ProfileOffCanvas.vue
web/src/plugins/vuetify.ts

Was able to delete a lot of no longer necessary code from this SFC due to the standardization of components and the utilization of Vuetify's date-picker
feat: upgrade court-list to use Vuetify
refactor: profile off canvas to use defineModel instead of emit
refactor: court-list to script setup composition api
https://vuejs.org/guide/components/v-model
https://vuetifyjs.com/en/components/date-inputs/
https://vuejs.org/api/sfc-script-setup

JASPER 167: Vuetify Court-list

---

web/package-lock.json
web/package.json

Bump Vitest version
Confirmed tests still run fine

Vitest 3.0.2 => 3.0.5

---

web/src/components/courtfilesearch/CourtFileSearchView.vue
web/src/components/courtlist/CourtList.vue
web/src/components/shared/Banner.vue
web/src/components/shared/Form/ActionButtons.vue
web/tests/components/shared/Banner.test.ts

Ticket details new requirements from the filters (ordering and appearances), this PR implements those requirements.
This PR also adds a new `banner` component to be re-used by our pages.
Ticket is not fully done with the completion of this PR, there will need to be 1 more PR after this one.
refactor: structure of court-file search filters
refactor: default location to empty
feat: new banner component
https://github.com/user-attachments/assets/b18f3fa1-f3f1-46e5-9480-8a4904d6bb45

JASPER 274: Court file search filter adjustments

---

infrastructure/cloud/environments/dev/webapp.tf
infrastructure/cloud/environments/prod/main.tf
infrastructure/cloud/environments/test/main.tf
infrastructure/cloud/modules/Cloudwatch/LogGroup/main.tf
infrastructure/cloud/modules/Cloudwatch/LogGroup/variables.tf
infrastructure/cloud/modules/IAM/main.tf
infrastructure/cloud/modules/WAF/main.tf
infrastructure/cloud/modules/WAF/outputs.tf
infrastructure/cloud/modules/WAF/variables.tf

Enables logging in WAF to help with investigating the intermittent issue the client is experiencing.

Enable WAF logging

---

api/Infrastructure/ServiceCollectionExtensions.cs
api/Services/CourtListService.cs
pcss-client/Clients/SearchDateServicesClient.cs
pcss-client/Models/Models.cs
web/src/components/courtlist/CourtListCard.vue
web/tests/components/courtList/CourtListCard.test.ts

Component needed to display the court-list card information.
This PR also adds the PCSS service client we are going to use to retrieve the court-room view of a court-list.
The client layer was generated from the NSwag tool.
**Test Configuration**:
If applicable

JASPER 240: Court-list Card and Service

---

infrastructure/cloud/modules/RDS/main.tf

Updated TF code to disable automated  backups

Disable automated backups and ignore tfsec issue

---

infrastructure/cloud/modules/RDS/main.tf

Apply disabling of backup right away without waiting for maintenance window.

Disable Auomated Backups

---

web/src/components/courtlist/CourtListSearch.vue
web/src/services/LocationService.ts
web/src/types/courtlist/index.ts
web/tests/components/courtList/CourtListSearch.test.ts

Introduce the search component that will be utilized by `CourtList.vue`. The plan is to leverage this component for the searching functionality, that way we can **drastically** cut down on the amount of code in `CourtList.vue`.
Next changes will be to `CourtList.vue` to utilize this component and be cleaned up.
Note also the "My Schedule" workflow is temporarily disabled until we determine best approach to this new workflow
feat: court-list search component
style: prettify interface declarations
test: court-list search tests
https://github.com/user-attachments/assets/eb59b81c-5900-47ab-80dc-0f748c8af99f

JASPER 237: Court-list Search Component

---

api/Controllers/CourtListController.cs
web/src/components/courtlist/CourtList.vue
web/src/components/courtlist/CourtListSearch.vue
web/src/components/shared/Banner.vue

This PR removes unnecessary code in favor of leveraging the [previously committed](https://github.com/bcgov/jasper/pull/196) court-list-search component to handle court-list searching for us.
This PR replaces the call we are making to JC-Interface to PCSS in favor of their court-list API.
https://github.com/user-attachments/assets/64f2dc20-2a71-4a77-a958-dd5e9d76eed4

JASPER 237: Court-list Page Search View

---

web/src/components/courtlist/CourtList.vue
web/src/components/courtlist/CourtListCard.vue
web/src/components/courtlist/CourtListSearch.vue
web/src/types/courtlist/index.ts
web/tests/components/courtList/CourtListCard.test.ts

This PR ties things together and results in the cards being displayed upon court-list search. Some adjustments were made to the card component to reduce it's props and to default some missing data.
A bug was also fixed which was causing the date selection through the date-picker to not update the banner date
https://github.com/user-attachments/assets/48b19779-2d25-4f1c-9ccb-1cb6dd23bf79

JASPER 240: Populate and display Court-list Cards

---

api/Controllers/PermissionsController.cs
api/Infrastructure/ServiceCollectionExtensions.cs
api/Mappers/UserManagementProfile.cs
api/Models/UserManagement/PermissionDto.cs
api/Models/UserManagement/PermissionUpdateDto.cs
api/Services/PermissionService.cs
api/Services/ServiceBase.cs
db/Repositories/PermissionRepository.cs
db/Repositories/RepositoryBase.cs

https://jira.justice.gov.bc.ca/browse/JASPER-315
- Add base repository pattern for doing CRUD operations against mongodb
- Use interface in Service and Repository classes to make writing unit test easier
- Use with `Permission` entity as a starting point
- Only `get` and `update` action for Permission controller
- Unit tests will be added after the team approve the pattern for doing CRUD operations.

JASPER-315: Permission read and update operations

---

web/src/components/case-details/CourtFilesSelector.vue
web/src/components/civil/CivilCaseDetails.vue
web/src/components/criminal/CriminalCaseDetails.vue
web/src/components/shared/CourtFilesSelector.vue
web/src/stores/CourtFileSearchStore.ts
web/tests/components/case-details/CourtFilesSelector.test.ts

Banner to display the currently viewable court files
Thanks to [Vue 3.4's Component v-model directives](https://vuejs.org/guide/components/v-model.html), we can cut down on code, stores and emits!
https://github.com/user-attachments/assets/841b9ab7-3d1b-4e4b-bdd5-f99bd74f388e

JASPER 277: Criminal Case Details Banner

---

infrastructure/cloud/modules/RDS/main.tf
infrastructure/cloud/modules/SecretsManager/output.tf

Fix to resolve infra pipeline build error

Update tf code to update pg db version to 16.4

---

api/Controllers/GroupsController.cs
api/Controllers/UsersController.cs
api/Infrastructure/ServiceCollectionExtensions.cs
api/Mappers/AccessControlManagementProfile.cs
api/Models/AccessControlManagement/GroupDto.cs
api/Models/AccessControlManagement/UserDto.cs
api/Services/GroupService.cs
api/Services/RoleService.cs
api/Services/UserService.cs
api/Validators/AccessControlManagementDtoValidator.cs
api/Validators/GroupDtoValidator.cs
api/Validators/PermissionDtoValidator.cs
api/Validators/RoleDtoValidator.cs
api/Validators/UserDtoValidator.cs
db/Models/Group.cs
db/Models/User.cs
db/Repositories/PermissionRepository.cs
tests/api/Controllers/GroupsControllerTests.cs
tests/api/Controllers/PermissionsControllerTests.cs
tests/api/Services/GroupServiceTests.cs
tests/api/Services/RoleServiceTests.cs
tests/api/Services/UserServiceTests.cs
tests/api/Validators/AccessControlManagementValidatorTests.cs
tests/api/Validators/GroupDtoValidatorTests.cs
tests/api/Validators/PermissionDtoValidatorTests.cs
tests/api/Validators/RoleDtoValidatorTests.cs
tests/api/Validators/UserDtoValidatorTests.cs

- https://jira.justice.gov.bc.ca/browse/JASPER-321
- https://jira.justice.gov.bc.ca/browse/JASPER-331
- Add CRUD operations for Group and User
- Update RoleService to handle `cascade` delete
- Add/Update unit tests for Validators, Services and Controllers

JASPER 321 and 331: Groups and Users CRUD Operations

---

web/src/components/case-details/CriminalSidePanel.vue
web/src/components/case-details/DivisionBadge.vue
web/src/components/case-details/Summary.vue
web/src/components/criminal/CriminalCaseDetails.vue
web/src/components/criminal/CriminalSentence.vue
web/src/components/shared/FileMarkers.vue
web/tests/components/case-details/CriminalSidePanel.test.ts
web/tests/components/case-details/DivisionBadge.test.ts
web/tests/components/case-details/Summary.test.ts
web/tests/components/shared/FileMarkers.test.ts

All components necessary to display the Criminal case details summary component.
I've continued with the methodology that I've been following thus far of splitting up the components into small, SOLID based files, which is why youll see 4 new components in this PR.
All components needed to display the Criminal details summary but have been developed in a way to handle more cases in the near future!

JASPER 281: Criminal Case Details Summary

---

api/Validators/UserDtoValidator.cs
tests/api/Validators/UserDtoValidatorTests.cs

Updates to handle `john@email` input and throw validation error.

Added stricter email validation check

---

api/Controllers/AuthController.cs
api/Controllers/UsersController.cs
api/Helpers/ClaimsTypes.cs
api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
api/Infrastructure/Authorization/AuthorizationServiceCollectionExtension.cs
api/Infrastructure/Authorization/PermissionHandler.cs
api/Infrastructure/Authorization/PermissionRequirement.cs
api/Infrastructure/Authorization/RequiresPermissionAttribute.cs
api/Infrastructure/Authorization/RequiresPermissionFilter.cs
api/Infrastructure/ServiceCollectionExtensions.cs
api/Mappers/AccessControlManagementProfile.cs
api/Models/AccessControlManagement/UserDto.cs
api/Services/UserService.cs
db/Contexts/JasperDbContext.cs
db/Seeders/UserSeeder.cs
docker/docker-compose.yaml
infrastructure/cloud/modules/SecretsManager/main.tf
infrastructure/cloud/modules/SecretsManager/output.tf
tests/api/Controllers/AuthControllerTests.cs
tests/api/Helpers/Extensions/ClaimsPrincipalExtensionsTests.cs
tests/api/Infrastructure/Authorization/PermissionHandlerTests.cs
tests/api/Services/UserServiceTests.cs

https://jira.justice.gov.bc.ca/browse/JASPER-312
- Add RequiresPermissin Attribute, Handler and Filter to enforce permissions check
- Update /auth/info to include user's firstname, lastname and permissions
- Update UsersController to require permissions for getting users
- Add Email to ClaimTypes
- Update UserSeeder to get seed data from env variable rather than hard coding email addresses
- Add/update unit tests of affected code

JASPER-312: Implement Enforcement of Access Control checks

---

web/public/styles/common.css
web/src/components/case-details/Accused/Accused.vue
web/src/components/case-details/Accused/AccusedPanel.vue
web/src/components/case-details/Accused/Ban.vue
web/src/components/case-details/CriminalSidePanel.vue
web/src/components/case-details/Summary.vue
web/src/utils/utils.ts
web/tests/components/case-details/Accused/Accused.test.ts
web/tests/components/case-details/Accused/AccusedPanel.test.ts
web/tests/components/case-details/Accused/Ban.test.ts
web/tests/components/case-details/CriminalSidePanel.test.ts

All components needed to display the accused criminal and youth panels on left hand side of case details, including ban modal

JASPER  283: Case-detail Accused Information

---

api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
api/Infrastructure/ServiceCollectionExtensions.cs

Add checks to skip initialization of features that needs mongodb

Fix authentication failure when logging in to JASPER

---

aws/services/apiService.ts
aws/services/httpService.ts
aws/tests/services/apiService.test.ts
openshift/sync-secrets.dc.yaml
pcss-client/Clients/ReportServicesClient.cs
web/src/components/courtlist/CourtList.vue
web/src/components/courtlist/CourtListSearch.vue
web/src/components/courtlist/CourtListTableSearchDialog.vue
web/tests/components/courtList/CourtListTableSearchDialog.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-239
- Implements the new requirements where the `location id`, `division`, `class`, `room` and `date` is pulled from the court list data.
- Opens multiple tabs per per report and combination above
- Return the response headers when calling the lambda functions. `content-disposition` is used when generating report to indicate the filename
- Simplified the parsing of secrets with the addition of default users which is in json object format (previously it was string)

JASPER-239: Court List - Print v2

---

web/src/components/courtlist/CourtList.vue

https://jira.justice.gov.bc.ca/browse/JASPER-239
During adhoc testing, an issue was found when court list data returned criminal data. Printing the court list and selecting `Additions`, the page shows an error. The updates fixes the issue to handle the checking and ensuring the correct parameter is passed to the endpoint
Error occurs when printing the court list with criminal data.

JASPER-239: Print Court List - Print 

---

web/src/components/case-details/Accused/Accused.vue
web/src/components/case-details/Accused/Bans.vue
web/src/components/case-details/AppearancesView.vue
web/src/components/case-details/CaseHeader.vue
web/src/components/case-details/Header.vue
web/src/components/courtlist/CourtListTable.vue
web/src/components/criminal/CriminalCaseDetails.vue
web/src/components/shared/AppearanceStatusChip.vue
web/src/utils/dateUtils.ts
web/src/utils/utils.ts
web/tests/components/case-details/AppearancesView.test.ts
web/tests/components/case-details/CaseHeader.test.ts
web/tests/components/shared/AppearanceStatusChip.test.ts
web/tests/utils/dateUtils.test.ts

This PR was already growing far too large, so I have decided to complete this feature in 2 PRs.
This PR introduces most of the logic and UI to be able to display the appearances in case-details.
This PR also introduces some new util functionality that is used by other components
feat: core functionality of case-details appearances view
feat: new util functions
https://github.com/user-attachments/assets/db31b791-f2da-41d3-a98d-9d9695b93382

JASPER 296: Case details appearances view core functionality

---

api/Controllers/AuthController.cs
api/Helpers/ClaimsTypes.cs
api/Helpers/Extensions/ClaimsPrincipalExtensions.cs
api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
api/Models/AccessControlManagement/UserDto.cs
api/Services/Files/CriminalFilesService.cs
api/Services/UserService.cs
db/Models/Role.cs
db/Seeders/GroupSeeder.cs
db/Seeders/RoleSeeder.cs
tests/api/Helpers/Extensions/ClaimsPrincipalExtensionsTests.cs
tests/api/Infrastructure/Authorization/PermissionHandlerTests.cs
tests/api/Services/UserServiceTests.cs
web/src/assets/colors.css
web/src/components/case-details/Accused/AccusedPanel.vue
web/src/components/case-details/AdjudicatorRestrictions/AdjudicatorRestriction.vue
web/src/components/case-details/AdjudicatorRestrictions/AdjudicatorRestrictionsPanel.vue
web/src/components/case-details/CriminalSidePanel.vue
web/src/components/criminal/CriminalCaseDetails.vue
web/src/main.ts
web/tests/components/case-details/AdjudicatorRestrictions/AdjudicatorRestriction.test.ts
web/tests/components/case-details/AdjudicatorRestrictions/AdjudicatorRestrictionsPanel.test.ts
web/tests/components/case-details/CriminalSidePanel.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-282
- Implement Adjudicator Restrictions section for Criminal. Backend performs currently logged on user role checking.
- Added `colors.css` to centralize colors being used throughout the application
https://github.com/user-attachments/assets/d3002746-f1a7-4dd3-a3bc-bb2dd715eb21

JASPER-282: Case details: Criminal - Adjudicator Restrictions

---

web/src/components/case-details/AppearancesView.vue
web/tests/components/case-details/AppearancesView.test.ts

https://github.com/user-attachments/assets/650675fa-2d0c-4a26-8a1c-075c6ec1b8d3

JASPER 296 - Case-details accused filter

---

web/public/styles/common.css
web/src/assets/colors.css
web/src/components/case-details/CaseHeader.vue
web/src/components/case-details/DocumentsView.vue
web/src/components/courtfilesearch/CourtFileSearchResult.vue
web/tests/components/case-details/CaseHeader.test.ts
web/tests/components/case-details/DocumentsView.test.ts

This PR does not cover all requirements of the ticket, I will be making 1 more PR after this one to finalize the work needed.
feat: core functionality of case details documents
refactor: disable sentence details until it's ready
style: pull generic styling out of court-file-search
style: thin data grouping header
https://github.com/user-attachments/assets/5147ea20-412d-43d4-bad8-d6d099bb6612

JASPER 280: Criminal case-details Documents view core functionality

---

api/Services/Files/CivilFilesService.cs
web/src/components/case-details/CivilSidePanel.vue
web/src/components/civil/CivilCaseDetails.vue
web/tests/components/case-details/CivilSidePanel.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-326
Implement Civil Adjudicator Restrictions section for JASPER.

JASPER-326: Case details: Civil - Adjudicator Restrictions

---

api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
web/src/assets/colors.css
web/src/components/case-details/civil/CivilSidePanel.vue
web/src/components/case-details/civil/CivilSummary.vue
web/src/components/case-details/civil/SheriffCommentsDialog.vue
web/src/components/case-details/common/CourtFilesSelector.vue
web/src/components/case-details/common/DivisionBadge.vue
web/src/components/case-details/criminal/CriminalSidePanel.vue
web/src/components/case-details/criminal/CriminalSummary.vue
web/src/components/civil/CivilCaseDetails.vue
web/tests/components/case-details/civil/CivilSidePanel.test.ts
web/tests/components/case-details/civil/CivilSummary.test.ts
web/tests/components/case-details/civil/SheriffComments.test.ts
web/tests/components/case-details/common/DivisionBadge.test.ts
web/tests/components/case-details/criminal/CriminalSidePanel.test.ts
web/tests/components/case-details/criminal/CriminalSummary.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-327
- Initial Civil Case Detail updates
- Added Civil Summary component including SheriffComments dialog
- Split `Summary` to `CriminalSummary` and `CivilSummary`
https://github.com/user-attachments/assets/ea5a5560-55ed-4c27-a8b0-de362321ae66

JASPER-327: Case details: Civil - Summary: Family and Small Claims

---

api/Controllers/CodesController.cs
api/Services/LookupService.cs
web/src/components/case-details/civil/CivilDocumentsView.vue
web/src/components/shared/EllipsesMenu.vue
web/src/components/shared/LabelWithTooltip.vue
web/src/services/LookupService.ts
web/src/stores/CommonStore.ts
web/src/types/common/index.ts
web/src/types/shared.ts
web/src/utils/utils.ts
web/tests/components/case-details/civil/CivilDocumentsView.test.ts

feat: consume new api endoint
feat: show role short description in civil table
feat: show all issues in tooltip

JASPER 328: Civil case-details FiledBy

---

web/src/components/case-details/civil/CivilDocumentsView.vue
web/tests/components/case-details/civil/CivilDocumentsView.test.ts

I forgot to include the count of each document type in this document filter
**Test Configuration**:
If applicable

Civil Case-details Document-type Filter Count

---

api/Services/Files/CivilFilesService.cs
web/src/components/case-details/civil/CivilDocumentsView.vue
web/src/components/case-details/civil/CivilSidePanel.vue
web/src/components/case-details/civil/children/Child.vue
web/src/components/case-details/civil/children/ChildrenPanel.vue
web/src/components/case-details/civil/parties/PartiesPanel.vue
web/src/components/case-details/civil/parties/Party.vue
web/src/components/case-details/common/CourtFilesSelector.vue
web/src/components/courtfilesearch/CourtFileSearchView.vue
web/src/types/common/index.ts
web/src/types/courtFileSearch/index.ts
web/tests/components/case-details/civil/CivilSidePanel.test.ts
web/tests/components/case-details/civil/children/Child.test.ts
web/tests/components/case-details/civil/children/ChildrenPanel.test.ts
web/tests/components/case-details/civil/parties/PartiesPanel.test.ts
web/tests/components/case-details/civil/parties/Party.test.ts
web/tests/components/case-details/common/CourtFilesSelector.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-325
- Implement Parties and Children sections for Family case details
- Move CourtClassEnum from `courtfilesearch` to `common`
- Update backend to only call court list when case detail is for Small Claims
https://github.com/user-attachments/assets/a8592b2e-fe89-4c01-bdcb-4f1a1e461ff1

JASPER-325: Case details: Civil - Family - Parties and Children Information

---

web/src/components/case-details/common/CaseHeader.vue
web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsDialog.vue
web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsTable.vue
web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsView.vue
web/tests/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsDialog.test.ts
web/tests/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsTable.test.ts
web/tests/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsView.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-297
Implement Criminal Sentence Order/Details Page, Table and Dialog
https://github.com/user-attachments/assets/42f0591e-f8ff-4fb8-86bb-8f1f51ea987c

JASPER-297: Case details: Criminal - Sentence/order details

---

web/src/components/case-details/common/accused/Accused.vue
web/src/components/case-details/criminal/CriminalSummary.vue
web/src/components/courtlist/CourtListTable.vue
web/src/components/shared/FileMarkers.vue
web/src/types/common/index.ts
web/tests/components/case-details/common/accused/Accused.test.ts
web/tests/components/case-details/criminal/CriminalSummary.test.ts
web/tests/components/shared/FileMarkers.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-380
- Update `FileMarkers` component to make it generic and reusable
- Move Criminal file markers to Accused/Participant level
https://github.com/user-attachments/assets/c8e78ffa-def9-4a3b-883c-aa0d12ea95dc

JASPER-380: Case Details: Criminal - File Markers to be moved to accused and updated

---

web/src/components/case-details/common/accused/AccusedPanel.vue
web/src/components/case-details/criminal/CriminalSidePanel.vue
web/src/utils/utils.ts
web/tests/components/case-details/common/accused/AccusedPanel.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-385
- Handle scenario when criminal case detail is not Adult or Youth
- Update related unit tests
https://github.com/user-attachments/assets/ed233674-824a-4fc1-a5dd-f2146774a35d

JASPER-385: Case Details: Criminal - Traffic Participants Header/Panel

---

api/Models/Civil/Detail/CivilParty.cs
api/Services/Files/CivilFilesService.cs
web/src/components/case-details/civil/children/Child.vue
web/src/types/civil/jsonTypes/index.ts
web/tests/components/case-details/civil/children/Child.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-349
Exposed `BirthDate` field from Court List API and map it to each party from Case Details
https://github.com/user-attachments/assets/c677ef8b-4af5-4172-9e3e-57cb6ee26ee1

JASPER-349: Case Details: Family - Birth Date and Age of Child

---

web/public/styles/common.css
web/src/components/case-details/civil/CivilSidePanel.vue
web/src/components/case-details/criminal/CriminalSidePanel.vue
web/src/components/civil/CivilCaseDetails.vue
web/src/components/criminal/CriminalCaseDetails.vue

https://github.com/user-attachments/assets/ad0975f9-5955-422b-9cf4-75f9e52c7396

JASPER 409: Scrollable case-details side-panel

---

api/Models/Civil/Detail/RedactedCivilFileDetailResponse.cs
web/src/components/case-details/civil/CivilSummary.vue
web/src/types/civil/jsonTypes/index.ts
web/tests/components/case-details/civil/CivilSummary.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-377
Expose cfcsaFileYn and use it to show CPA pill
ℹ️ The `FLA` chip is TBD and the team decided to work on adding the `CPA` chip for now.
https://github.com/user-attachments/assets/6fbfc4f5-18db-4e52-a052-f51079620b81

JASPER-377: Case details: Civil - Summary: CPA/FLA Marker

---

web/src/components/civil/CivilCaseDetails.vue

https://jira.justice.gov.bc.ca/browse/JASPER-416
- Simplify the assigning of boolean value to isSealed and docIsSealed
- Reset to default values when new case detail is being loaded
- Convert b-modal to v-dialog

JASPER-416: Case Details: "Sealed" message showing on all files once a sealed file is loaded.

---

web/public/styles/common.css
web/src/components/courtlist/CourtList.vue
web/src/components/courtlist/CourtListTable.vue
web/src/components/courtlist/CourtListTableActionBarGroup.vue
web/src/components/shared/TooltipIcon.vue
web/src/components/shared/table/ActionBar.vue
web/src/utils/utils.ts
web/tests/components/courtList/CourtListTableActionBarGroup.test.ts
web/tests/components/shared/table/ActionBar.test.ts

Updates to court-list are as follows:
Added grouping based off court classes
Added various icons to new icon column
Added action bars based off court class selections
Fixed issue where civil parties were not showing up
Adjusted column widths

JASPER 339 - Court-list updates

---

api/Models/Calendar/CalendarDay.cs
api/Models/Calendar/CalendarDayActivity.cs
api/Services/DashboardService.cs
tests/api/Services/DashboardServiceTests.cs
web/src/components/dashboard/MyCalendar.vue
web/src/components/dashboard/MyCalendarDay.vue
web/src/components/dashboard/MyCalendarDayExpanded.vue
web/src/types/CalendarDayActivity.ts
web/tests/components/dashboard/MyCalendarDayExpanded.test.ts

https://jira.justice.gov.bc.ca/browse/JASPER-86
https://jira.justice.gov.bc.ca/browse/JASPER-478
This is the expanded panel implementation in the My Schedule of the Dashboard page. The day cell is expanded to show more information about the activity.
https://github.com/user-attachments/assets/f14e33e2-7c32-4424-a7c9-3cd63899edf6

JASPER-86 and 478: Dashboard - My Schedule - Click to Expand a Date & Adjudicator Restrictions

---

web/src/components/case-details/civil/CivilDocumentsView.vue
web/src/components/case-details/civil/documents/AllDocuments.vue
web/src/components/case-details/civil/documents/JudicialBinder.vue
web/src/components/shared/ConfirmButton.vue
web/tests/components/case-details/civil/documents/JudicialBinder.test.ts
web/tests/components/shared/ConfirmButton.test.ts

https://github.com/user-attachments/assets/02699429-892d-4fff-aa3c-8070d0338ba6

JASPER 454 - Delete Judicial Binder/Remove Associated Documents

---

web/src/components/case-details/civil/CivilDocumentsView.vue
web/src/components/case-details/civil/documents/JudicialBinder.vue
web/src/components/case-details/criminal/CriminalDocumentsView.vue
web/src/plugins/vuetify.ts
web/tests/components/case-details/civil/CivilDocumentsView.test.ts
web/tests/components/case-details/civil/documents/JudicialBinder.test.ts

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
https://github.com/user-attachments/assets/20ef3d13-fd82-4c78-b4ac-8e2e5df7a270

JASPER 454 - Remove selected binder docs

---

api/Controllers/FilesController.cs
api/Documents/Strategies/FileStrategy.cs
api/Models/Document/PdfDocumentDetailsRequest.cs
web/src/components/case-details/civil/CivilDocumentsView.vue
web/src/components/case-details/criminal/CriminalDocumentsView.vue
web/src/components/courtlist/CourtList.vue
web/src/components/documents/DocumentUtils.ts
web/src/components/documents/NutrientContainer.vue
web/src/components/documents/models/GeneratePdf.ts
web/src/components/shared.ts
web/src/services/FilesService.ts
web/src/stores/PDFViewerStore.ts
web/src/types/shared.ts
web/tests/components/documents/DocumentUtils.test.ts
web/tests/components/documents/NutrientContainer.test.ts

This endpoint provides a way for the FE to utilize the document merging capabilities of the BE Nutrient SDK
Note: This flow does not currently support the outline feature, this will have to be taken care of in another PR.

JASPER 526: Expose new document generation endpoint

---

api/Models/Calendar/CalendarDayActivity.cs
api/Services/DashboardService.cs
tests/api/Services/DashboardServiceTests.cs

https://jira.justice.gov.bc.ca/browse/JASPER-402
Business agreed to simplify the sorting logic to order by location name rather than region name.

JASPER-402: Dashboard - Court Calendar - Date Box

---

web/src/services/HttpService.ts

https://jira.justice.gov.bc.ca/browse/JASPER-557
Initial update to remove the 10-second timeout in the frontend. Requests that take longer will no longer be automatically cancelled.
We’d like to deploy this to production as soon as possible to see if it improves the user experience and helps us avoid unnecessary reloads.

JASPER-557: Performance Tuning: Case Details Load (Timeout Removal)

---

web/src/components/shared.ts

Always open new tab when viewing merged documents

---

.github/workflows/publish-api-select.yml
.github/workflows/publish-api.yml
.github/workflows/publish-lambdas-select.yml
.github/workflows/publish-web-select.yml

Include the JIRA ticket # and link here  
New publish workflows have been added which provide options to select the target environment and source branch for deployment
- [X ] New feature (non-breaking change which adds functionality)
**Test Configuration**:
If applicable
Put any doc references here

Add environment and branch selection to Publish pipelines

---

web/src/components/case-details/criminal/CriminalDocumentsView.vue
web/src/components/courtlist/CourtListCriminalDetails.vue
web/tests/components/case-details/criminal/CriminalDocumentsView.test.ts
web/tests/components/courtList/CourtListCriminalDetails.test.ts

Fixes # [588](https://jira.justice.gov.bc.ca/browse/JASPER-588)

JASPER 588: Fix key-documents perfected bail data not showing

---

web/src/components/courtlist/CourtList.vue
web/src/components/courtlist/CourtListTable.vue

JASPER 541/542: Court-list sorting, ordering and counting

---

web/package-lock.json
web/package.json

Vuetify release [3.10.1](https://github.com/vuetifyjs/vuetify/releases/tag/v3.10.1) [issue 21096](https://github.com/vuetifyjs/vuetify/issues/21096) which was preventing us from upgrading.
As this is a big version upgrade I tested JASPER and have confirmed things are working as expecting

Upgrade Vuetify

---

web/src/components/courtlist/CourtList.vue
web/src/components/dashboard/panels/DashboardPanels.vue
web/src/components/dashboard/panels/reserved-judgements/ReservedJudgementTable.vue
web/src/types/ReservedJudgement.ts
web/tests/components/dashboard/panels/DashboardPanels.test.ts

Relies on https://github.com/bcgov/jasper/pull/541 merging.
fix: issue where two windows would open during print court-list

JASPER 88: Show full ReservedJudgement table data

---

web/src/components/dashboard/Dashboard.vue
web/src/components/dashboard/panels/DashboardPanels.vue
web/src/components/dashboard/panels/reserved-judgements/ReservedJudgementTable.vue

Updates to show Reserved Judgments data related to the current/selected user.
https://github.com/user-attachments/assets/243d41c6-9f2d-4f6a-91fe-7c54624f0fd5

Reload Reserved Judgments when User Selects Different Judge

---

api/api.csproj
db/db.csproj
jc-interface-client/jc-interface-client.csproj
pcss-client/pcss-client.csproj
tests/tests.csproj

Update packages to the latest. This PR should also close the following dependabot PRs (https://github.com/bcgov/jasper/pull/539, https://github.com/bcgov/jasper/pull/501).
All existing unit tests passed and performed smoke test locally.

Upgrade BE packages

---

web/src/components/courtlist/CourtListTable.vue
web/src/components/shared/TooltipIcon.vue

JASPER 546: Show court-list schedule notes
