bcgov/jasper

api/Controllers/AuthController.cs, api/Helpers/XForwardedForHelper.cs, api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs, tests/api/Helpers/XForwardedForHelperTests.cs, tests/tests.csproj
N/A
Issue encountered after the KeyCloak SSO Upgrade in DEV/TEST environments. It was found that SCV/JASPER is not sanitizing the url paths that is later on combined to generate the complete URL.
- Refactor BuildUrlString to use UriBuilder to generate complete URL
- Updated callers to reference the new function signature
- Added unit tests and Bogus library to make it easier to generate random test data
=> Fix for SSO Login Issue

web/src/components/courtfilesearch/CourtFileSearchResult.vue, web/src/components/criminal/CriminalAdjudicatorRestrictions.vue, web/src/components/criminal/CriminalDocumentsView.vue, web/src/components/criminal/CriminalFutureAppearancesTable.vue, web/src/components/criminal/CriminalParticipants.vue, web/src/components/criminal/CriminalPastAppearancesTable.vue, web/src/components/criminal/CriminalWitnesses.vue, web/src/components/shared/table/ActionBar.vue, web/src/plugins/vuetify.ts
Necessary changes to facilitate the matching of the court search table to the wireframe!
Adjusted some of the non-working case detail tables (those are the files changed that youll see under the 'criminal' folder in this PR) as well that broke as a result of migrating to vue-bootstrap-next. More on that in 'Documentation References' section of this PR
feat: court file search table
feat: action bar slot
fix: case detail tables not displaying
refactor: upgrade court-file-result sfc to composition api
style: data table defaults
Reason for the `sortBy` changes
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/table.html#sorting
=> JASPER 178: Court file search result

.devcontainer/Dockerfile, infrastructure/cloud/README.md
- Adds the AWS Session Manager Plugin required to use `aws ecs execute-command` to shell into running containers.
- Adds example documentation.
=> Add support for AWS ECS Exec

web/src/App.vue, web/src/components/shared/Snackbar.vue, web/src/services/HttpService.ts, web/src/stores/SnackbarStore.ts, web/src/stores/index.ts, web/tests/components/shared/Snackbar.test.ts, web/tests/stores/SnackbarStore.test.ts
I began working on upgrading Court-list to Vuetify and noticed this page also had its own unhandled exception handling logic.
I decided to move the logic out and encapsulate it into the httpservice class itself, that way any api call made by a page that experiences a server exception will raise a [snack ](https://vuetifyjs.com/en/components/snackbars/) (toast) message the same way
feat: snackbar store
feat: raise snacks globally
https://vuetifyjs.com/en/components/snackbars/
=> JASPER 262: Globally Handle Exceptions with Snackbar

web/src/plugins/vuetify.ts
A previous [PR ](https://github.com/bcgov/jasper/pull/135/files#diff-b9409e644568d2b55e23be531e98022fa61119ad2f4ea1afbf8bfde23ddaac4b) accidentally removed the defaults for Vuetify's data-table.
This PR adds it back in
fix: add back in Vuetify data table default
=> JASPER: Add back in accidentally removed V-Data-Table default

.github/workflows/actions/build-web/action.yml, web/src/components/courtfilesearch/CourtFileSearchView.vue, web/src/components/criminal/CriminalDocumentsView.vue, web/src/components/shared.ts
The package we currently rely on to base64 our urls has [issues](https://github.com/brianloveswords/base64url/issues) regarding latest JS frameworks.
This PR forgoes that package and uses our own base64url functionality.
We should at some point completely deprecate this package from the project and use the method I introduced here.
fix: criminal document download functionality
refactor: remove unneeded error handling from courtfilesearch
refactor: prettify shared.ts
build: remove if exists flag from unit-tests in FE build
Fixes # [268](https://jag.gov.bc.ca/jira/browse/JASPER-268)  
base64url package -https://github.com/brianloveswords/base64url
=> JASPER 268: Fix Criminal-document download functionality

web/src/components/courtfilesearch/CourtFileSearchView.vue
When searching for File number we want to require File number and Location.
Also snuck in a change to force refresh the v-data-table's data by dropping the store on page refresh.
=> JASPER 270: Location/File# required when searching for File#

api/Services/Files/FilesService.cs
It seems we can throw a header on our request that lets JC know we want the file to be flattened. This it isnt 100% going to get a flattened version of the file youre requesting, just a flattened version if it exists.
I expect this to lower the amount of incompatible files, but not completely solve the issue.
=> JASPER 272: Request flattened files from JC where available

web/src/components/courtfilesearch/CourtFileSearchView.vue
We were filtering for the wrong file-number search criteria when the class was set to anything but criminal
fix: filter by fileNumber when non criminal search
refactor: hide class dropdown when non criminal search
=> JASPER 287: Fix inability to filter Family/Claims by FileNumber

web/package-lock.json, web/package.json, web/src/App.vue, web/src/components/civil/CivilAdjudicatorRestrictions.vue, web/src/components/civil/CivilFutureAppearances.vue, web/src/components/civil/CivilPastAppearances.vue, web/src/components/courtfilesearch/CourtFileSearchResult.vue, web/src/components/courtfilesearch/CourtFileSearchView.vue, web/src/stores/CourtFileSearchStore.ts, web/src/stores/index.ts
With the help of [pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate) we can utilize a cached version of pinia on command. This allows us to now caching the court-file-search results and permits the open in new tab workflow.
The changes to `App.vue` are so the court-file-search tab is highlited when navigating to the case files
The rest of the changes in this PR relate to fixing more broken `b-tables` that broke as a result of moving from 
vue-bootstrap-next 2.0 => 3.0+
https://github.com/prazdevs/pinia-plugin-persistedstate
=> JASPER 274: Open Case-details in new tab/Fix more erroring b-tables

aws/services/apiService.ts, aws/services/httpService.ts, aws/tests/services/apiService.test.ts, aws/tests/services/httpService.test.ts, aws/tests/util.test.ts, aws/util.ts, infrastructure/cloud/modules/APIGateway/main.tf
https://jira.justice.gov.bc.ca/browse/JASPER-289  
- Added binary media type `application/octet-stream` in APIGW infra code
- Handle `application/octet-stream` requests
- Passed AxiosRequestConfig instead of headers only
- Updated unit tests
=> JASPER-289: Lambda Function Integration

.github/workflows/actions/deploy-app/action.yml, infrastructure/cloud/modules/ECS/TaskDefinition/main.tf, infrastructure/cloud/modules/ECS/TaskDefinition/variables.tf
https://jira.justice.gov.bc.ca/browse/JASPER-291
- Updates to deploy app pipelines to store the recently deployed `web` or `api` image to AWS Param Store
- Updated Terraform code to retrieve the saved image and use it on the ECS TD when infra code is deployed.
=> JASPER-291: Use SSM Parameter to store the latest deployed image name

web/src/components/courtlist/CourtListSearch.vue, web/src/components/shared/Snackbar.vue, web/src/stores/SnackbarStore.ts, web/tests/components/courtList/CourtListSearch.test.ts, web/tests/stores/SnackbarStore.test.ts
This PR implements auto refreshing into the court-list page. After 9 minutes of inactivity (no adjusting filters, no searching or swapping days) the page will display a notification letting the user know that in 1 minute the page will refresh. After that 1 minute is up, the page will take the current filters and make a query.
If 9 minutes pass and the warning is visible and the user takes an action on the page, all timers will be pushed back 10 minutes and the warning snack message will be hidden.
If more timer work is needed in JASPER then I will extract this logic out to it's own component(s).
feat: auto refresh court-list after 10 minutes
feat: show warning to user refresh will happen after 9 minutes
feat: snackbar now accepts a timeout param …
=> JASPER 267: Court-list auto-refresh and message

web/src/components/courtlist/CourtList.vue, web/src/components/courtlist/CourtListSearch.vue, web/src/components/courtlist/CourtListTableSearch.vue, web/src/components/shared/Banner.vue, web/tests/components/courtList/CourtListTableSearch.test.ts, web/tests/components/shared/Banner.test.ts
This PR allows the ability to filter the retrieved data from the court-list search. Fuzzy search, time (AM/PM) and file status filters.
The AM/PM search will filter out unmatching cards(and tables), whereas the other filters only filter the table data directly.
Right now the table implementation has been omitted until we get `appearances` data back from the court-list api call.
The implementation of filtering everything including the omitted tables is done in this PR that way we are prepared once the table is ready to be displayed in the system.
feat: introduce in place court-list data filtering
refactor: adjust how color is considered in banner component
style: lower elevation on court-list search component
=> JASPER 238: Court-list data filter

web/index.html, web/src/components/civil/CivilCaseDetails.vue
Stylesheets were being referenced incorrectly `./` => `/` which was causing an inability to find the css files at times.
This PR also hooks up the civil details flow to the new selector changes made in this [PR](https://github.com/bcgov/jasper/pull/218)
fix: fix incorrect css import
fix: hook up civil details to selector changes
=> Fix incorrect stylesheet import

web/src/components/case-details/Accused/Accused.vue, web/src/components/case-details/Accused/Bans.vue, web/src/components/criminal/CriminalCaseDetails.vue, web/tests/components/case-details/Accused/Accused.test.ts, web/tests/components/case-details/Accused/Bans.test.ts
Ban modal was displaying incorrect information
refactor: display different properties
=> JASPER 283: Display correct Ban information

api/Models/Civil/Detail/CivilParty.cs, api/Models/Location/Location.cs, api/Services/Files/CivilFilesService.cs, api/Services/LocationService.cs, tests/api/Models/Location/LocationTests.cs, web/src/assets/colors.css, web/src/components/case-details/civil/CivilSidePanel.vue, web/src/components/case-details/civil/parties/PartiesPanel.vue, web/src/components/case-details/civil/parties/Party.vue, web/src/components/shared/LabelWithTooltip.vue, web/src/types/civil/jsonTypes/index.ts, web/tests/components/case-details/civil/CivilSidePanel.test.ts, web/tests/components/case-details/civil/parties/PartiesPanel.test.ts, web/tests/components/case-details/civil/parties/Party.test.ts, web/tests/components/shared/LabelWithTooltip.test.ts
https://jira.justice.gov.bc.ca/browse/JASPER-324
- Add CourtList call when loading a Civil case detail to get party alias
- Update Location to include AgencyIdentifierCd as the value is used in JC Courtlist endpoint
- Add Party section in Civil case details page
- Add LabelWithTooltip component to handle scenarios where a list of string needs to display with plus sign and the rest is on tooltip
_NOTE: Data has been duplicated for `alias` and `counsel` to show how the tooltip and +1 label will look like_
https://github.com/user-attachments/assets/64c4b5ed-05e0-40a2-b207-f3ff0cc7739e
=> JASPER-324: Case details: Civil - Small Claims - Parties Information

web/src/components/case-details/civil/CivilDocumentsView.vue
We decided to remove this column until it is fully implemented to avoid questions.
Since we will need it in the future I opted for commenting it out instead of removing it entirely.
refactor: remove judicial binder column from case-details
=> Remove Judicial-binder column from Civil-details

api/api.csproj, db/db.csproj, jc-interface-client/jc-interface-client.csproj, pcss-client/pcss-client.csproj, tests/tests.csproj
MongoDb team released a new version of MongoDb.EntityFrameworkCore [v9.0 ](https://github.com/mongodb/mongo-efcore-provider/releases/tag/v9.0.0) 2 weeks ago. Upgrading to the latest version including other backend dependencies so that we are using v9.0 across all projects/dependencies.
Tested this version locally and deployed the feature branch in DEV and it appears the upgrade did not break anything.
=> Upgrade backend packages to latest including MongoDb.EFCore to v9.0

web/src/components/case-details/common/AppearancesView.vue, web/src/components/case-details/common/CaseHeader.vue, web/src/components/shared/Form/NameFilter.vue, web/src/types/civil/jsonTypes/index.ts, web/src/types/criminal/jsonTypes/index.ts, web/src/types/shared.ts, web/tests/components/case-details/common/AppearancesView.test.ts, web/tests/components/shared/Form/NameFilter.test.ts
I was able to re-use the appearances view for both criminal and civil(including small claims)
The only difference is the lack of accused names, so I added in some checks to exclude all info relating to that from the appearances component
This involved having me extract out some of the repeated interfaces into some base shared interfaces.
https://github.com/user-attachments/assets/880a6724-0c7f-495e-b68f-01ffbe4686a7
=> JASPER 323: Civil-details Appearances View

web/src/components/case-details/criminal/CriminalSummary.vue, web/src/components/courtlist/CourtListTable.vue, web/tests/components/case-details/criminal/CriminalSummary.test.ts
=> JASPER 375: Move 'days' text to case-age label and header

web/src/components/shared/FileMarkers.vue, web/tests/components/shared/FileMarkers.test.ts
Fixed incorrect tooltip for DO and W file markers that was found during Sprint demo.
https://github.com/user-attachments/assets/d33d9432-7bf3-49d4-8dc1-2194d664e949
=> Fix file marker description for DO and W

web/src/components/case-details/common/AppearancesView.vue, web/src/components/case-details/criminal/appearances/AppearanceCharges.vue, web/src/components/case-details/criminal/appearances/AppearanceCounsel.vue, web/src/components/case-details/criminal/appearances/AppearanceMethods.vue, web/src/components/case-details/criminal/appearances/CriminalAppearanceDetails.vue, web/src/components/criminal/CriminalCaseDetails.vue, web/src/services/FilesService.ts, web/src/types/criminal/jsonTypes/index.ts, web/tests/components/case-details/common/AppearancesView.test.ts, web/tests/components/case-details/criminal/appearances/AppearanceMethods.test.ts, web/tests/components/case-details/criminal/appearances/CriminalAppearanceDetails.test.ts
Add ability to drop down a criminal appearance in the appearances table to view it's information at a finer detail.
The counsel tab will not be hooked up until we are able to call the PCSS endpoint to get that info.
This PR also changes the default behavior for how the UI displays no appearances. Before the component was just empty, but now it will show an empty table and a card above it that reads "Appearances".
https://github.com/user-attachments/assets/eabc815b-aa5c-4273-89c0-27a19b2f0b07
=> JASPER 346: Criminal appearance details

web/src/components/courtlist/CourtListTable.vue, web/src/components/shared/FileMarkers.vue, web/src/types/common/index.ts, web/src/types/courtlist/index.ts, web/tests/components/shared/FileMarkers.test.ts
https://jira.justice.gov.bc.ca/browse/JASPER-382
Update Court List to render appropriate file markers for criminal, sc, mva, enforcement, family and with adjudicator restrictions
_Note: Current implementation only shows `ADJ` file marker when there are AR. We are waiting for confirmation from client if this is the desired behavior._
https://github.com/user-attachments/assets/e11ec9a9-0649-4cab-ae10-c680681bb0cc
=> JASPER-382: Court List - Update File Markers

web/src/components/case-details/civil/parties/Party.vue, web/src/components/case-details/common/accused/Accused.vue, web/src/components/case-details/criminal/CriminalSummary.vue
=> JASPER 408: Reduce whitespace in Case-Details side-panel

.devcontainer/devcontainer.json
Yesterday, I encountered an issue (could not resolve manifest for aws-cdk) when loading JASPER in devcontainer. As per my research, `devcontainers-contrib` is no longer advisable to be used and should be replaced by `devcontainers-extra`.
More info can be found here: https://github.com/devcontainers-extra/features/issues/123#issuecomment-2933883193
=> Migrate from devcontainers-contrib to devcontainers-extra

web/src/components/case-details/criminal/sentence-order-details/SentenceOrderDetailsTable.vue
We were using the default max-row amount for `v-data-tabel`, which is 10.
I have updated this table to a `v-data-table-virtual` which has a much larger limit and is more performant when not using data that needs to be manipulated in any way.
Also set a max-height for the table to stay in line with the other tables on the other tabs.
Fixes # [424](https://jira.justice.gov.bc.ca/browse/JASPER-424)
=> JASPER 424: Sentence-order - Remove 10 item table limit

web/src/components/shared/FileMarkers.vue, web/tests/components/shared/FileMarkers.test.ts
We no longer want to display file markers for an appearance when they are not enabled
Court-list
Case-details
=> JASPER 421: Only show file markers that are "set"

api/Services/Files/CriminalFilesService.cs, web/package-lock.json, web/package.json, web/src/components/case-details/common/AppearancesView.vue, web/src/components/courtfilesearch/CourtFileSearchResult.vue, web/src/components/courtlist/CourtListCriminalDetails.vue, web/src/components/courtlist/CourtListTable.vue, web/src/services/FilesService.ts, web/tests/components/courtList/CourtListCriminalDetails.test.ts
Get criminal appearance details on court-list row expand.
Currently there is a [bug ](https://github.com/vuetifyjs/vuetify/issues/21096)in Vuetify that can crash when `return-object` is true and trying to expand a row. Due to this I have downgraded the Vuetify version to one that does not have this bug.
This PR also allows the ordering of dates in court-file search
https://github.com/user-attachments/assets/d2d53cb2-7fa1-4eb3-9745-5955ba7f9ced
=> JASPER 350: Court-list criminal appearance expanded panel

web/public/styles/common.css, web/src/components/case-details/civil/CivilSummary.vue, web/src/components/case-details/common/CourtFilesSelector.vue, web/src/components/case-details/criminal/CriminalSummary.vue, web/src/components/civil/CivilCaseDetails.vue, web/src/components/courtfilesearch/CourtFileSearchResult.vue, web/src/components/courtfilesearch/CourtFileSearchView.vue, web/src/components/criminal/CriminalCaseDetails.vue, web/src/components/shared/CopyToClipboard.vue, web/src/constants/labelClasses.ts, web/tests/components/case-details/criminal/CriminalSummary.test.ts, web/tests/components/shared/CopyToClipboard.test.ts
-Added a component that is comprised of an icon, when on click copies the desired text to the users clipboard. Upon click notifies the user this copy action took place.
-Force the file selector tabs to be centered
-Fixed an issue where clearing the court-file-search division filter did not clear out selected table items
-Fixed an issue where file number was not being properly utilized in case-details tabs
https://github.com/user-attachments/assets/f6ee91ea-a5e8-465b-a7d7-3504325e1435
=> JASPER 474: Copyable file-number and center tabs

api/Services/Files/CivilFilesService.cs, web/src/components/case-details/civil/parties/Party.vue, web/tests/components/case-details/civil/parties/Party.test.ts
https://jira.justice.gov.bc.ca/browse/JASPER-467
- Show Alias if available and for SC, MVA and Legislated court class only
- Update backend to include cases with MVA and Legislated court class when retrieving aliases via court list endpoint
- Use the appearance's court agency id when querying for court list
https://github.com/user-attachments/assets/6a1a8cbd-1d0d-4cdc-8b5e-878c327cee60
=> JASPER-467: Case Details: Civil - Appearance of Aliases

web/package-lock.json, web/package.json, web/src/components/case-details/civil/CivilDocumentsView.vue, web/src/components/case-details/civil/documents/JudicialBinder.vue, web/src/components/courtlist/CourtListTable.vue, web/tests/components/case-details/civil/children/Child.test.ts, web/tests/components/case-details/civil/documents/JudicialBinder.test.ts
After spending some time researching various approaches, I decided to leverage this library to accomplish what JASPER needs
[GitHub - SortableJS/vue.draggable.next](https://github.com/SortableJS/vue.draggable.next)
build: add vuenext draggable
feat: add ability to reorder documents within a judicial binder
feat: add ability to view case-details from court-list
https://github.com/user-attachments/assets/2150141c-b84b-4156-a354-30d7ae9e7872
=> JASPER 455: Judicial binder reordering

api/Models/Criminal/AppearanceDetail/CriminalAppearanceDetail.cs, api/Services/Files/CriminalFilesService.cs, web/src/components/courtlist/CourtList.vue, web/src/components/courtlist/CourtListCriminalDetails.vue, web/src/types/criminal/jsonTypes/index.ts, web/tests/components/courtList/CourtListCriminalDetails.test.ts
We were mistakenly referencing "Initiating" documents instead of "All" documents when building out the list of key-documents.
Because of this we weren't getting the full list of available key documents.
=> Fix Court-list appearance details not showing all key-documents

web/src/components/case-details/civil/CivilDocumentsView.vue, web/src/components/case-details/civil/documents/JudicialBinder.vue, web/src/components/civil/CivilCaseDetails.vue, web/src/components/criminal/CriminalCaseDetails.vue
feat: open judicial docs in nutrient
fix: remove duplicate case-details call on page load
=> JASPER 465: Open Judicial-Binder in Nutrient

web/src/components/courtlist/CourtListCard.vue, web/src/components/courtlist/CourtListTable.vue, web/src/components/courtlist/CourtListTableActionBarGroup.vue, web/tests/components/courtList/CourtListTableActionBarGroup.test.ts
https://jira.justice.gov.bc.ca/browse/JASPER-569
- Remove `View Shared Folder` buttons in Court List
- Hide `View document bundle` button in Court List action bar
- Add behavior to allow viewing of case details from the selected appearance in Court List
https://github.com/user-attachments/assets/7ae392f2-022b-4f1a-b2f6-565e355d658b
=> JASPER-569: Court List: Temporary updates to elements on page 

web/src/components/case-details/civil/CivilDocumentsView.vue, web/src/components/case-details/criminal/CriminalDocumentsView.vue, web/src/components/courtlist/CourtList.vue, web/src/components/documents/DocumentUtils.ts, web/src/components/documents/NutrientContainer.vue, web/src/components/documents/models/GeneratePdf.ts, web/src/components/shared.ts, web/src/stores/PDFViewerStore.ts, web/tests/components/documents/DocumentUtils.test.ts, web/tests/components/documents/NutrientContainer.test.ts
This PR adds the FE capability to create and display the document outlines
The outline API is only exposed in the FE Nutrient SDK. This means it is entirely the FE's responsibility. The BE is only responsible for receiving pdf generation requests and squashing them all down into one document.
This is phase 1 of the outlines. More changes will come, but phase 1 needs to be done in time for the 2nd.
=> JASPER 470 - Nutrient Viewer Document Outline

api/Helpers/ClaimsTypes.cs, api/Helpers/Extensions/ClaimsPrincipalExtensions.cs, api/Infrastructure/Authentication/AuthenticationServiceCollectionExtension.cs
This update uses the `pcss_judge_id` value to be able to load users PCSS data. If the claim is not populated, the default user will be loaded.
=> Use new claim to easily map the current user to PCSS user

api/Infrastructure/Mappings/DocumentCategoryMapping.cs, web/src/components/case-details/civil/CivilDocumentsView.vue, web/src/components/case-details/civil/appearances/ScheduledDocuments.vue, web/src/components/case-details/civil/documents/AllDocuments.vue, web/src/components/case-details/civil/documents/JudicialBinder.vue, web/tests/components/case-details/civil/CivilDocumentsView.test.ts
https://jira.justice.gov.bc.ca/browse/JASPER-548
- Fixes the Documents dropdown to use Categories instead of Document Types
- Updates Court List Scheduled Documents to show Document Type intead of Category
- Format the category name to show the first letter as capital while the rest are lower case. ROPs and CRSs is skipped.
- Some fixes to small bugs (value in Issue column, removing a document from binder via ActionBar)
https://github.com/user-attachments/assets/0ba4f728-e53a-486d-85ac-6777cfcfbd16
=> JASPER-548: Case Details: Civil: Document Filtering by Category

web/src/components/case-details/civil/CivilDocumentsView.vue, web/src/components/case-details/criminal/CriminalDocumentsView.vue, web/src/components/courtlist/CourtList.vue, web/src/components/documents/NutrientContainer.vue, web/src/components/shared.ts, web/src/stores/PDFViewerStore.ts, web/src/types/shared.ts, web/tests/components/documents/NutrientContainer.test.ts
Auto expand outline groups
Elements can be under a single parent now
Fixed court-list report not generating accurately
Made the implementation more generic
=> JASPER 577: Nutrient updates

web/index.html, web/src/components/case-details/civil/appearances/ScheduledDocuments.vue, web/src/components/civil/CivilAppearanceDetails.vue, web/src/components/courtlist/CourtListCriminalDetails.vue, web/src/components/courtlist/CourtListTable.vue, web/tests/components/case-details/civil/appearances/ScheduledDocuments.test.ts, web/tests/components/civil/CivilAppearanceDetails.test.ts, web/tests/components/courtList/CourtListCriminalDetails.test.ts
Can now view individual documents in court-list appearance details
Updated nutrient-web viewer version
=> JASPER 585: View court-list appearance details documents

.github/workflows/actions/build-api/action.yml, .github/workflows/build-and-test-api.yml
This should run the `dotnet test` command in the right directory where `tests.csproj` lives.
=> Fix directory where dotnet test command executes

web/src/components/courtlist/CourtListTableActionBarGroup.vue, web/src/utils/utils.ts, web/tests/utils/utils.test.ts
Fixes # [614](https://jira.justice.gov.bc.ca/browse/JASPER-614)
=> JASPER 614: Show 'View Key-documents' for all criminal appearances

web/src/components/dashboard/CalendarToolbar.vue, web/src/components/dashboard/CourtToday.vue, web/src/components/dashboard/Dashboard.vue, web/src/components/dashboard/court-calendar/CourtCalendar.vue, web/src/components/dashboard/my-calendar/MyCalendar.vue, web/tests/components/dashboard/CalendarToolbar.test.ts, web/tests/components/dashboard/court-calendar/CourtCalendar.test.ts, web/tests/components/dashboard/my-calendar/MyCalendar.test.ts
https://jira.justice.gov.bc.ca/browse/JASPER-556
Add `previous` and `next` buttons to both My Calendar and Court Calendar to make navigation easier. This previous and next feature is supported in all views (weekly, 2-week and monthly).
https://github.com/user-attachments/assets/332fa386-bbe1-40dc-af66-df89c28b3118
=> JASPER-556: Dashboard: Addition of date navigation chevrons to move forward or backward
